version: '3.8'

services:
  postgres:
    image: postgres:14
    container_name: gpay-postgres
    restart: always
    ports:
      - "5434:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: gpay
    volumes:
      - postgres-data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: gpay-app
    restart: always
    ports:
      - "3000:3000"
    depends_on:
      - postgres
    environment:
      - DATABASE_URL=postgresql://postgres:postgres@postgres:5432/gpay?schema=public
      - NEXTAUTH_SECRET=gpay-nextauth-secret-key-2024-development
      - NEXTAUTH_URL=http://localhost:3000

volumes:
  postgres-data:
